version: '2.3'

services:
  mongodb:
    image: 'mongo:${DEVDOCKER_MONGODB_VERSION:-5.0.24}'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb-data:/data/db'
    networks:
      - node-network
    restart: unless-stopped

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      env_file: .env
    volumes:
      - .:/usr/src/app
    networks:
      - node-network
    command: npm run start


volumes:
  mongodb-data:

networks:
  node-network:
    driver: bridge
